name: unit-tests
on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: ['1.20.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Src Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
        id: go

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: Check
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          make check

      - name: Tests
        env:
          GOPROXY: "https://proxy.golang.org"
          CI: true
        run: make test
